blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed


urlpatterns = [
	#url(r'^$', views.PostListView.as_view(), name='post_list'),
	url(r'^$', views.post_list, name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$',views.post_list,name='post_list_by_tag'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
	url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
	url(r'^search/$', views.post_search, name='post_search'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
	'posts': PostSitemap,
}


urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
	url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
#告诉Django在blog/路径下包含了blog应用中的urls.py定义的URL模式。可给它们一个命名空间叫做blog，这样可以方便的引用这个URLs组。

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.core.urlresolvers import reverse


class PublishedManager(models.Manager):

	def get_queryset(self):#get_queryset()是返回执行过的查询集（QuerySet）的方法
		return super(PublishedManager,
					 self).get_queryset().filter(status='published')


class Post(models.Model):
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
	)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, related_name='blog_posts')
	body = models.TextField()#这是帖子的主体。它是TextField，在SQL数据库中被转化成TEXT。
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,
							  choices=STATUS_CHOICES,
							  default='draft')
	#这个字段表示当前帖子的展示状态。我们使用了一个choices参数，这样这个字段的值只能是给予的选择参数中的某一个值。
	#（注：传入元组，比如(1,2)，那么该字段只能选择1或者2，没有其他值可以选择）
	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()#这个tags管理器（manager）允许你给Post对象添加，获取以及移除标签。

	class Meta:
		ordering = ('-publish',)
		#Django查询数据库的时候默认返回的是根据publish字段进行降序排列过的结果。我们使用负号来指定进行降序排列

	def __str__(self):
		return self.title
		#str()方法是当前对象默认的可读表现

	def get_absolute_url(self):
		return reverse('blog:post_detail',
					   args=[self.publish.year,
							 self.publish.strftime('%m'),
							 self.publish.strftime('%d'),
							 self.slug])


class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Comment by{} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)#
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False,
							   widget=forms.Textarea)


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
	query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.db.models import Count
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from haystack.query import SearchQuerySet

def post_list(request, tag_slug=None):
	'''post_list视图将request对象作为参数。所有的的视图都需要这个参数.另有一个可选的tag_slug参数，默认是一个None值。这个参数会带进URL中.'''
	object_list = Post.published.all()#这个视图中，通过使用之前创建的published管理器,获取到了所有状态为已发布的帖子
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)#取回所有发布状态的帖子，假如给予标签slug，我们通过get_object_or_404()用给定的slug来获取标签对象.
		object_list = object_list.filter(tags__in=[tag])
	
	paginator = Paginator(object_list, 3)#每页3帖子
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		#如果页面不是整数，则传递第一个页面
		posts = paginator.page(1)
	except EmptyPage:
		#如果页面超出了范围，交付结果的最后一页
		posts = Paginator.page(paginator.num_pages)
	return render(request,#使用Django提供的快捷方法render()通过给予的模板（template）来渲染帖子列。这个函数将request对象作为参数,模板路径以及变量来渲染的给予的模板
				  'blog/post/list.html',
				  {'page': page,#返回一个渲染文本（一般是HTML代码）HttpResponse对象。render()方法考虑到了请求内容，这样任何模板内容处理器设置的变量都可以带入给予的模板中。
				   'posts': posts,
				  'tag': tag})


class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
	'''这个视图使用year，month，day以及post作为参数通过给予slug和日期来获取到一篇已经发布的帖子,注意，当我们创建Post模型时，我们给slgu字段添加了unique_for_date参数。
	这样可以确保在给予的日期中只有一个帖子会带有一个slug，因此，能通过日期和slug取回单独的帖子'''
	post = get_object_or_404(Post, slug=post,#通过使用get_object_or_404()快捷方法来检索期望的Post。这个函数能取回匹配给予的参数的对象，或者当没有匹配的对象时返回一个404异常。
							 status='published',#状态为已发表
							 publish__year=year,
							 publish__month=month,
							 publish__day=day)
	comments = post.comments.filter(active=True)
	new_comment = None

	if request.method == 'POST':
		comment_form = CommentForm(data=requset.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()
	
	post_tags_ids = post.tags.values_list('id', flat=True)
	'''取回了一个包含当前帖子所有标签的ID的Python列表。values_list() 查询集返回包含给定的字段值的元祖。
	我们传给元祖flat=True来获取一个简单的列表类似[1,2,3,...]。'''
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)#获取所有包含这些标签的帖子排除了当前的帖子
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
	'''使用Count聚合函数来生成一个计算字段same_tags，该字段包含与查询到的所有 标签共享的标签数量。
	通过共享的标签数量来排序（降序）结果并且通过publish字段来挑选拥有相同共享标签数量的帖子中的最近的一篇帖子。
	我们对返回的结果进行切片只保留最前面的4篇帖子。'''
	return render(request,#使用render()快捷方法来使用一个模板去渲染取回的帖子
				  'blog/post/detail.html',
				  {'post': post,
				  'comments': comments,
				  'new_comment': new_comment,
				  'comment_form': comment_form,
				  'similar_posts': similar_posts})


def post_share(request, post_id):
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False
	cd = None
	if request.method == 'POST':
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_url(
				post.get_absolute_url())
			'''通过使用post.get_absolute_url()方法来获取到帖子的绝对路径,
				将这个绝对路径作为request.build_absolute_uri()的输入值来构建一个完整的包含了HTTP schema和主机名的url,
				通过使用验证过的表单数据来构建email的主题和消息内容并最终给表单to字段中包含的所有email地址发送email'''
			subject = '{}({})recommends you reading "{}"'.format(cd['name'],cd['email'], post.title)
			message = 'read "{} at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
			send_mail(subject, message, 'admin@myblog.com',[cd['to']])
			sent = True
		else:
			form = EmailPostForm()
		return render(request, 'blog/post/share.html',
					  {'post': post,
					   'form': form,
					   'sent': sent,
					   'cd': cd})


def post_search(request):
	form = SearchForm()
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			cd = form.cleaned_data
			results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
			total_results = results.count()

		return render(request, 'blog/post/search.html',
					  {'form': form,
					   'cd': cd,
					   'results': results,
					   'total_results': total_results})
	return render(request,'blog/post/search.html',{'form':form})

blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
	<div id="content">
		{% block content %}
		{% endblock %}
	</div>
	<div id="sidebar">
		<h2>My blog</h2>
		<p>这是我的博客.目前为止，我已经写了 {% total_posts %} 篇博客.</p>
		<p><a href="{% url "blog:post_feed" %}">订阅我的RSS feed</a></p>
		<h3>最新的博客</h3>
		{% show_latest_posts 3 %}
		<h3>最多评论博客</h3>
		{% get_most_commented_posts as most_commented_posts %}
		<ul>
			{% for post in most_commented_posts %}
				<li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
			{% endfor %}
		</ul>
	</div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<h1>{{ post.title }}</h1>
	<p class="date">Published {{ post.publish }} by {{ post.author }}</p>
	{{ post.body|markdown }}

	<p>
		<a href="{% url "blog:post_share" post.id %}">Share this post</a>
	</p>

	<h2>Similar posts</h2>
	{% for post in similar_posts %}
		<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
	{% empty %}
		There are no similar posts yet.
	{% endfor %}

	{% with comments.count as total_comments %}
		<h2>
			{{ total_comments }} comment{{ total_comments|pluralize }}
		</h2>
	{% endwith %}

	{% for comment in comments %}
		<div class="comment">
			<p class="info">
				Comment {{ forloop.counter }} by {{ comment.name }}
				{{ comment.created }}
			</p>
			{{ comment.body|linebreaks }}
		</div>
	{% empty %}
		<p>There are no comments yet.</p>
	{% endfor %}

	{% if new_comment %}
		<h2>Your comment has been added.</h2>
	{% else %}
		<h2>Add a new comment</h2>
		<form action="." method="post">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="Add comment"></p>
		</form>
	{% endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
	<li>
		<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
	</li>
	{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}
{% block content %}

	{% include "pagination.html" with page=posts %}

	<h1>My Blog</h1>

	{% if tag %}
		<h2>Posts tagged with "{{ tag.name }}"</h2>
	{% endif %}
	<p class="tags">
		Tags:
		{% for tag in post.tags.all %}
			<a href="{% url "blog:post_list_by_tag" tag.slug %}">
				{{ tag.name }}
			</a>
			{% if not forloop.last %}, {% endif %}
		{% endfor %}
	</p>


	{% for post in posts %}
		<h2>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</h2>
		<p class="date">
		Published {{ post.publish }} by {{ post.author }}
		</p>
		{{ post.body|markdown|truncatewords_html:30 }}
		<p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
	{% endfor %}

{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if "query" in request.GET %}
        <h1>Posts containing "{{ cd.query }}"</h1>
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        {% for result in results %}
            {% with post=result.object %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>           
                {{ post.body|truncatewords:5 }}
            {% endwith %}
            {% empty %}
                <p>There are no results for your query.</p>
        {% endfor %}    
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ cd.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number }}">Previous</a>
		{% endif %}
		<span class="current">
			Page {{ page.number }} of {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
			<a href="?page={{ page.next_page_number }}">Next</a>
		{% endif %}
	</span>
</div>